### ISSUE TITLE
Update UI up to latest prototype

### ISSUE THREAD

**Issue by andrii-i** [jupytercalpoly/jupyterlab-notifications#30]
User interface (UI) should be updated in line with [latest Figma prototype iteration](https://www.figma.com/proto/nRUWHVE78mPyqV5nzFrBgS/Notifications-UI?node-id=22%3A297&scaling=min-zoom&page-id=8%3A2&starting-point-node-id=13%3A443)

_Preview:_
![image](https://user-images.githubusercontent.com/26686070/138735567-2c7ad341-e476-45bc-855c-38b9f7145825.png)

**Comment by marissathai** [comment]
clean up front end designs to match with Figma

**Comment by marissathai** [comment]
will have to make new figma iteration before sending mockup designs to Andri or Harshit

**Comment by andrii-i** [comment]
As discussed during meetings / UI review with @marissathai:

- [x] Fix spacing underneath notifications stack header when opened
- [x] Take out small subject header since it's on the main stack
- [x] include “Clear All” if the sections have a notification card underneath
- [x] If the section is already empty then the “Clear All” shouldn’t show up
- [x] Blocking pop up snack bar should disappear in 25 seconds
- [x] width of pop up snack bar should end up on edge of the Notification Center sidebar
- [x] Extended width would make the message only have two lines and would convince the users that its a shorter message so they have time to read it all, instead of three lines that would turn off the user's interest
- [x] User Joined Session <-- all words should be all capitalized
- [x] because the subject header is in bold it makes sense for it to be capitalized to convince users that it's an important message
