### ISSUE TITLE
Add new/old messages sorting

### ISSUE THREAD

**Issue by andrii-i** [jupytercalpoly/jupyterlab-notifications#64]
Divide all notifications into "NEW" and "EARLIER" sections depending on when it was created. "NEW" notifications are notifications created within the last 24 hours

_Preview:_
![image](https://user-images.githubusercontent.com/26686070/138736831-703e6b9e-49bf-493d-99e2-1222c8f468b3.png)

**Comment by marissathai** [comment]
figma iteration already has messages divided up based on time, look at figma iteration 4 for screens

**Comment by andrii-i** [comment]
@marissathai how should timestamp look if notification was created more than 7 days ago? (currently we only show day and time so it is not necessary clear which week/date, not sure if it is a problem)

**Comment by marissathai** [comment]
@andrii-i the time stamp would just say "a week ago", if its more than a week then "2 weeks ago" and continue on from there.
