### ISSUE TITLE
Add logical time

### ISSUE THREAD

**Issue by andrii-i** [jupytercalpoly/jupyterlab-notifications#65]
Currently, field all notifications [are timestamped by the server ](https://github.com/jupytercalpoly/jupyterlab-notifications/blob/main/jupyterlab_notifications/handlers.py#L132) when notification is passed to the server for the first time "created" field on INotificationResponse object. To avoid inconsistencies between time on different machines, we should investigate adding logical time instead.

Refer to [OpenAPI Specification](https://github.com/jupytercalpoly/jupyterlab-notifications/blob/main/api/api.json) for API details.

**Comment by hxmittal** [comment]
Upon investigation, we discovered that the server timestamp does not cause inconsistencies as the server time is in UNIX time which is consistent for both the server and the client. The frontend for the user accurately receives notifications based on the UNIX time and then converts into local time (using browser data) and stays consistent throughout timezones.
