### ISSUE TITLE
Decide on ability of users to customize notification settings

### ISSUE THREAD

**Issue by andrii-i** [jupytercalpoly/jupyterlab-notifications#9]

**Comment by marissathai** [comment]
Users are able to dismiss particular notifications from the Notification Center view and they are able to unsubscribe from a type of notification that would pop up as a toast or reside in their Notification Center. If needed users are able to re-subscribe in the settings panel by switching on a toggle switch connected to the type of notifications they've unsubscribed.

**Comment by andrii-i** [comment]
Do users have access to any other settings?
